### PR TITLE
Update index.md/README.md

### PR DESCRIPTION
**Pull request by roansong**
General language updates and tweaks

### CODE REVIEW

**Comment by collerek** [comment]
Awesome, thank you! 😃 

Can you change Italian to Croatian (though i fixed that already)?

**Comment by collerek** [comment]
And can you copy the index.md from docs to readme.md please (it's just select all + copy + paste -> same content).

Thanks!

**Comment by roansong** [comment]
Looks like a few more changes came across from index.md to README.md

**Comment by collerek** [comment]
Thank you! :)

**Pull request merged**
