### PR TITLE
Fix timezones and add support for pydantic 1.9.0

### PR DESCRIPTION
**Pull request by collerek**
# 0.10.24

## ✨ Features

* Add `post_bulk_update` signal (by @ponytailer - thanks!) [#524](https://github.com/collerek/ormar/pull/524)

## 🐛 Fixes

* Fix support for `pydantic==1.9.0` [#502](https://github.com/collerek/ormar/issues/502)
* Fix timezone issues with datetime [#504](https://github.com/collerek/ormar/issues/504)
* Remove literal binds in query generation to unblock postgres arrays [#/tophat/ormar-postgres-extensions/9](https://github.com/tophat/ormar-postgres-extensions/pull/9)
* Fix bulk update for `JSON` fields [#519](https://github.com/collerek/ormar/issues/519)

## 💬 Other

* Improve performance of `bulk_create` by bypassing `databases` `execute_many` suboptimal implementation. (by @Mng-dev-ai thanks!) [#520](https://github.com/collerek/ormar/pull/520) 
* Bump min. required `databases` version for sqlalchemy 1.4 to `>=5.4`.

### CODE REVIEW

**Comment by Goldziher** [comment]
@collerek - I suggest you consider also adding python 3.10 support and dropping python 3.6.

**Comment by collerek** [comment]
@Goldziher I wanted to do this some time ago but I think `databases` still don't support python 3.10 so I'm blocked.

**Comment by Goldziher** [comment]
Are you sure this is a blocker? 3.10 probably doesn't break anything, but it will give a new syntax for those who use it. I suggest updating the test matrix and seeing.

**Comment by collerek** [comment]
> Are you sure this is a blocker? 3.10 probably doesn't break anything, but it will give a new syntax for those who use it. I suggest updating the test matrix and seeing.

Ok it was aiomysql at that time not databases: https://github.com/collerek/ormar/runs/4141248426?check_suite_focus=true.
Can check if it works now.

**Pull request merged**
