### PR TITLE
 use the dict to store the receivers in signal

### PR DESCRIPTION
**Pull request by ponytailer**
- use the dict to store the receivers in signal  
- SignalEmitter extends dict to save the signals

 @collerek

### CODE REVIEW

**Comment by ponytailer** [comment]
The `Signal` is simple and useful. it should be common, should move the `sender` into the `kwargs` maybe ?

**Comment by collerek** [comment]
I avoid adding dialect-specific fields to `ormar`, `JSONB` is already supported in an awesome package: https://github.com/tophat/ormar-postgres-extensions by @etimberg. 

I will check the dict signals, don't remember why it was a list.

**Comment by ponytailer** [comment]
> https://github.com/tophat/ormar-postgres-extensions

Fine, I remove the `jsonb`, maybe should support here, not the extra lib.

**Comment by ponytailer** [comment]
> The `Signal` is simple and useful. it should be common, should move the `sender` into the `kwargs` maybe ? @collerek

And this ?

**Comment by collerek** [comment]
Awesome, thanks!

**Pull request merged**
