### PR TITLE
support(bulk-create): add raise_error flag when bulk-create empty models

### PR DESCRIPTION
**Pull request by ponytailer**
- add raise_error flag #843

### CODE REVIEW

**Review by Abdeldjalil-H — CHANGES_REQUESTED** [review]
I think it is better to return when `raise_error=False` and the objects list is empty.

**Comment by collerek** [comment]
@ponytailer We can do it inline with `bulk_update` and simply raise and exception on empty list (and release as 0.12.0 since it's breaking). Thanks!

**Comment by ponytailer** [comment]
> ### **[collerek](/collerek) ** commented [2分钟前](#issuecomment-1260714795)

Yes, if you will have the big version recently,  raise exception simply when it's empty.

**Review by collerek — APPROVED** [review]

**Comment by collerek** [comment]
Thanks!

**Pull request merged**
