### PR TITLE
Lifespan

### PR DESCRIPTION
**Pull request by mekanix**
It's hard with tests as when first fails, some of the next ones fail, too. I checked them individually, and every test I changed passes like that. That probably means I need better `lifespan()` but for now I just wanted to show my intention and ask if I'm going in the right way?

### CODE REVIEW

**Comment by collerek** [comment]
Yep, that seems like the way to go. Note also that `app.state` is deprecated so it should be like global variables (https://github.com/tiangolo/fastapi/issues/81#issuecomment-473677039) with db instead of custom properties, or something like a dependency with cache (https://fastapi.tiangolo.com/advanced/settings/#creating-the-settings-only-once-with-lru_cache).

**Comment by collerek** [comment]
Ah almost forgot, I would like to switch to async tests for fastapi too, that means going away from TestClient from starlette and switching to httpx. So we need httpx in dev dependencies, and a client fixture in each file, something like this:

```python
@pytest_asyncio.fixture()
async def client(request: pytest.FixtureRequest) -> AsyncIterator[AsyncClient]:
    transport = ASGITransport(app=app, client=("1.2.3.4", 123), raise_app_exceptions=False)
    async with AsyncClient(transport=transport) as client, LifespanManager(app):
        yield client
```

Note that for tests and lifetime, you need an additional dev dependency `asgi_lifespan` with `LifespanManager` like used above and AsyncClient from httpx. Then switch all requests to async using this client like `await client.get(...)` (and tests need to be marked with `@pytest.mark.asyncio`).

**Comment by gmekicaxcient** [comment]
One thing at a time. First I need lifespan to work. If I put database instance as global var, all tests register their models and of course, there are name collisions. I need to drop database or drop all tables in tear down, first. Let me experiment with it for a bit and once it works, async will be easier.

**Comment by collerek** [comment]
Sure thing! :)

Btw by global, I meant scope -> so global to the module/file not one for all tests (global for the app). 
So each lifespan refers to its own global `_database = Database(...)` somewhere below the imports in each of the files.

**Comment by mekanix** [comment]
That would be nice, but then I can't reach `_database` from `lifespan`. As I said, let me experiment a little and see how to do this.

**Comment by collerek** [comment]
Not sure what you mean you cannot access it -> sample of what I aim for is here: https://github.com/collerek/ormar/blob/a8b9fcea0cde3cdc6b619961134c410d6fea8406/tests/test_fastapi/test_binary_fields.py just changed to lifespan. Realized httpx and asgi)lifespan deps are already there too, forgot about this 🤣

**Comment by mekanix** [comment]
I didn't fix all the tests, but I think you can see what I want to do. I intend to finish what I've started tomorrow, unless you have some objections/comments.

**Comment by collerek** [comment]
Yeah it seems fine, will save a lot of duplication. Not sure if we need engine in the OrmarConfig as it's used only in tests to create/ drop db (in production one should use migrations) and is not used anywhere in the ormar itself. But at the same time it's optional so could probably just sit there if anyone wants it, need to think about it 🤔

**Comment by mekanix** [comment]
I squashed all commits and made all tests use new functions `create_config`, `lifespan` and `init_tests`. Benchmarks are failing, but they were failing even before I changed anything. As a matter of fact, some of the benchmarks pass now, which is a progress. Anyway, I can't figure out why the two tests fail
```
FAILED tests/test_fastapi/test_binary_fields.py::test_read_main - AssertionError: assert 'w4Mo' == 'Ã('
FAILED tests/test_fastapi/test_json_field_fastapi.py::test_setting_values_after_init - sqlite3.OperationalError: table things has no column named js
```

Can you please look into that? Second failure is strange, because if you run only that test, it passes, but I can't figure out where I'm not cleaning what I should clean up.

As for the `engine` being part of config, I would say it's a good thing to have it there. As ormar is sqlaclhemy consumer, and every sqlaclhemy config consists of `database`, `metadata` and `engine`, I think this makes it complete and exposes `engine` for developers if they ever need it. For tests it's obvious why we need it, as we need to drag it along with `database` and `metadata` somehow. Also, if tests are any indication of possible use case, other people will need `engine`, too.

**Comment by collerek** [comment]
You need `create_test_database = init_tests(base_ormar_config)` in each of the files as there are models with duplicated table names. When you add it to `test_json_field_fastapi.py` file it passes, binary test also has model with table named things that's why those two conflict. Please add this line to all of the files so they are self contained (it can cause hard to track bugs in other cases, each file is considered a stand alone tests.)

**Comment by mekanix** [comment]
Ah, great catch! It was already 4am when I sent this PR, no wonder I missed it. I'll fix in few hours when I finish some chores. Thank you!

**Comment by mekanix** [comment]
I initialized all tests, but I still get two errors
```
FAILED tests/test_fastapi/test_binary_fields.py::test_read_main - AssertionError: assert 'w4Mo' == 'Ã('
ERROR tests/test_model_methods/test_populate_default_values.py::test_populate_default_values - sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "Default": syntax error
```
Any clues? I can't see what's wrong, honestly.

**Comment by collerek** [comment]
I modified the workflows to run also tests again pydantic_v2 branch, can you push something here, I guess it should be picked up. Cause I run the tests on local after checking out your pr and all did pass for me. If the gh will not pick up the changes because v2 branch is not merged yet then you should be able to change it here I guess but let's see.

**Comment by mekanix** [comment]
Ah, I was speaking too soon. I only see MySQL failing, so I'll try to setup MySQL test on my desktop.

**Comment by collerek** [comment]
mysql is first, then pg and sqlite at the end. You can use docker to test it -> you have sample docker-compose and commands in makefile

**Comment by collerek** [comment]
but it seems you forgot lifetime method in test_fastapi with nested defaults, as for the model methods tests I believe it should be `text("'Default Name'")` with double quotes, not sure how that passes now 😅

**Comment by mekanix** [comment]
We have a saying in Serbian (which is almost the same as Croatian) "you and I make a good one" :o) With the latest error, I guess it's some PostgreSQL throttling?

**Comment by collerek** [comment]
that's a bit weird - you did add some create calls but was it that many?
We can test the increased number of connections, add 
`command: postgres -c 'max_connections=1000'` in `.github/workflows/test-package.yml`
so it will become:
```yaml
      postgres:
        image: postgres:10.8
        command: postgres -c 'max_connections=1000'
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testsuite
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
```

**Comment by collerek** [comment]
Ah shit command is not supported in github actions :/ You need to follow the steps here: https://stackoverflow.com/questions/70673766/how-to-increase-max-connection-in-github-action-postgres

**Comment by collerek** [comment]
it's `--host` instead of `--hostname` https://www.postgresql.org/docs/current/app-psql.html

**Comment by collerek** [comment]
You are missing db name, check https://stackoverflow.com/questions/32824388/postgresql-remotely-connecting-to-postgres-instance-using-psql-command

**Comment by mekanix** [comment]
I don't know if I would ever catch that. Nice! Now looking at next error, how is postgresql supposed to be restarted via docker if we're inside docker already?

**Comment by collerek** [comment]
Add name to options so container have static name instead of random docker one and use that one. You can follow the guide here: https://github.com/remarkablemark/remarkablemark.github.io/blob/master/_posts/2022/2022-05-12-github-actions-postgresql-increase-max-connections-and-shared-buffers.md

**Comment by mekanix** [comment]
Are we OK with this regression in benchmark tests?

**Review by collerek — APPROVED** [review]
Great job! That was a lot more changes than I expected (didn't think you would refactor to remove duplication for all tests) but more than welcome! Saved me a ton of work and I really appreciate it! Thank you! :) 

As for the benchmarks - yeah degradation is fine, I still need to figure out if they are reliable enough :)

**Comment by mekanix** [comment]
First of all, thank you for the great ORM! Second of all, thank you for the kind words! Third of all, what should I do next? The two that stand out are ` Code cleanup` and `Fix line numbers highlighted in docs examples after reformat`. When I say stand out, I mean the rest of the requirements sound like I need way more familiarity with ormar code than I currently have. Please do correct me if I'm wrong and advise on the next step(s).

**Comment by collerek** [comment]
If you would like to help more the `Fix line numbers highlighted in docs examples after reformat` is a good candidate. 😁 

When you open docs of the current version there are highlighted some lines in the code examples. i.e line 10 below
image

(screen comes from https://collerek.github.io/ormar/models/)

If you checkout wip_pydantic_v2 branch and issue `mkdocs serve` you will see that now this line is line 9 not 10.

image

So in file `docs/models/index.md` the lines:

image

Should be corrected to `Python hl_lines="9"`

That needs to be checked/corrected for all code samples in the docs (and it's  a nice way to get to know ormar better)

**Comment by mekanix** [comment]
```
grep -r hl_lines | wc -l
      59
```
Not bad! I'll take it.

**Pull request merged**
