### PR TITLE
Fix collerek/ormar#588 Bug in queryset count() method

### LINKED ISSUE #588: Using "count()" on table with `select_related` gives the total of all rows instead of the count of the primary select
**Describe the bug**
This is mainly apparent in pagination, where you want the count of the primary objects. The count currently takes the count of all rows, which will include the joined rows. So if an object has many related objects, the count will be the number of related objects.

**To Reproduce**
I have added a test to check count in the "test_aggr" file on my forked branch, as well as some potential code to fix the issue.
I wasn't sure if you wanted to introduce a breaking change, or if the original functionality was necessary for something. I ended up changing the default, but adding a "distinct" keyword for those who depend on the legacy behavior.

**Expected behavior**
Count should return the count of the primary rows, not the total number of rows including left joins

**Versions (please complete the following information):**
 - Postgres 11.4
 - Python 3.8.11
 - ormar 0.10.22

### PR DESCRIPTION
**Pull request by erichaydel**
Fixes #588

### CODE REVIEW

**Comment by collerek** [comment]
Thanks for catching that! :)
This is still breaking as the default behavior changes but soon we should release a 0.11 version anyway.

**Comment by collerek** [comment]
Can you please update the docs too to include the new parameter (check the quick start in index, & readme, update queries/aggregations)?

**Comment by erichaydel** [comment]
Done! Let me know how that looks

**Comment by erichaydel** [comment]
It seems like it died immediately on Python 3.7, but I'm not sure why. Is there any good way to read the log output?

**Pull request merged**
